# Pods com rótulos e anotações
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: TechChallenge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: TechChallenge
  template:
    metadata:
      labels:
        app: TechChallenge
      annotations:
        version: "1.0"
        maintainer: "team@techchallenge.com"
    spec:
      containers:
        - name: backend
          image: thithips/backend:1.0
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: app-config
          volumeMounts:
            - mountPath: "/app/data"
              name: backend-data
      volumes:
        - name: backend-data
          persistentVolumeClaim:
            claimName: backend-pvc

---
# Service para o Backend
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: TechChallenge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
# ConfigMap para configurações
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  connection-string: "data source=ViniciusNasc\VSQL;initial catalog=TechChallengeFiap2;user id=sa;password=MyPass@word;TrustServerCertificate=True;Trusted_Connection=False"

---
# Volume para persistência de dados
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/backend"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
