global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api-techChallenge"
    static_configs:
      - targets: ["tech-challenge-api:80"]

  - job_name: "rabbitmq"
    static_configs:
      - targets: ["techChallengeMQ:15692"] # Porta RabbitMQ prometheus plugin
        
  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]