// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechChallengeFiap.Infrastructure.Contexto;

#nullable disable

namespace TechChallengeFiap.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContexto))]
    partial class ApplicationDbContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechChallengeFiap.Domain.Entities.Contato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<Guid>("IdDDD")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("VARCHAR(11)");

                    b.HasKey("Id");

                    b.HasIndex("IdDDD");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("TechChallengeFiap.Domain.Entities.DDD", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdEstado")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("NumeroDDD")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("IdEstado");

                    b.ToTable("DDDs");
                });

            modelBuilder.Entity("TechChallengeFiap.Domain.Entities.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)");

                    b.Property<Guid>("IdRegiao")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdRegiao");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77df935a-ca53-4ffd-94ae-c197e016ccf0"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Acre",
                            IdRegiao = new Guid("91ea2869-3fb0-4c39-8583-f420f8d48fa5"),
                            Uf = "AC"
                        },
                        new
                        {
                            Id = new Guid("8f7ae6df-d6a5-4d86-8994-e64002ee557e"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Alagoas",
                            IdRegiao = new Guid("78fa8876-6c2d-4a09-b981-f77538f18fbb"),
                            Uf = "AL"
                        },
                        new
                        {
                            Id = new Guid("489e8c02-00cc-4113-8dab-8e44ead66543"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Amapa",
                            IdRegiao = new Guid("91ea2869-3fb0-4c39-8583-f420f8d48fa5"),
                            Uf = "AP"
                        },
                        new
                        {
                            Id = new Guid("2b3cb7d6-f792-4ae6-b068-38da911997d8"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Amazonas",
                            IdRegiao = new Guid("91ea2869-3fb0-4c39-8583-f420f8d48fa5"),
                            Uf = "AM"
                        },
                        new
                        {
                            Id = new Guid("3a8ca4e0-eb66-452c-b4d5-dd4b428f3cbf"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Bahia",
                            IdRegiao = new Guid("78fa8876-6c2d-4a09-b981-f77538f18fbb"),
                            Uf = "BA"
                        },
                        new
                        {
                            Id = new Guid("38cdbdab-bc0b-4f2e-b561-500a1708d8da"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Ceara",
                            IdRegiao = new Guid("78fa8876-6c2d-4a09-b981-f77538f18fbb"),
                            Uf = "CE"
                        },
                        new
                        {
                            Id = new Guid("20792100-80af-49a8-8195-f7c36441c38d"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Espirito Santo",
                            IdRegiao = new Guid("6fb578f8-5176-4906-a805-3a100adde0c9"),
                            Uf = "ES"
                        },
                        new
                        {
                            Id = new Guid("8c797ec8-ea24-4bc5-9288-56a6cb14a8ef"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Goias",
                            IdRegiao = new Guid("8b985725-487b-4a32-92a5-cb708f44c54b"),
                            Uf = "GO"
                        },
                        new
                        {
                            Id = new Guid("7451a52c-8460-4f6a-bca6-7573b9a44759"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Maranhao",
                            IdRegiao = new Guid("78fa8876-6c2d-4a09-b981-f77538f18fbb"),
                            Uf = "MA"
                        },
                        new
                        {
                            Id = new Guid("786e47a5-f326-40bc-afb5-0af531e7af9f"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Mato Grosso",
                            IdRegiao = new Guid("8b985725-487b-4a32-92a5-cb708f44c54b"),
                            Uf = "MT"
                        },
                        new
                        {
                            Id = new Guid("c4dc2412-b190-411a-8352-0a857b7e327b"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Mato Grosso do Sul",
                            IdRegiao = new Guid("8b985725-487b-4a32-92a5-cb708f44c54b"),
                            Uf = "MS"
                        },
                        new
                        {
                            Id = new Guid("3b72bc3f-4613-4313-963c-9621db443e32"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Minas Gerais",
                            IdRegiao = new Guid("6fb578f8-5176-4906-a805-3a100adde0c9"),
                            Uf = "MG"
                        },
                        new
                        {
                            Id = new Guid("06759cc3-cf92-49fe-9d98-a8eacb5ee621"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Para",
                            IdRegiao = new Guid("91ea2869-3fb0-4c39-8583-f420f8d48fa5"),
                            Uf = "PA"
                        },
                        new
                        {
                            Id = new Guid("d4fdba6b-ee4c-4c06-b8d7-7dcbbc0d02fa"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Paraiba",
                            IdRegiao = new Guid("78fa8876-6c2d-4a09-b981-f77538f18fbb"),
                            Uf = "PB"
                        },
                        new
                        {
                            Id = new Guid("ef7e5a58-45a2-4b80-8e13-fdeefb2f5a5e"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Parana",
                            IdRegiao = new Guid("667589e6-12e3-44de-86cb-141058365c78"),
                            Uf = "PR"
                        },
                        new
                        {
                            Id = new Guid("451ecb2b-0ba5-48c7-84ff-32772634c258"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Pernambuco",
                            IdRegiao = new Guid("78fa8876-6c2d-4a09-b981-f77538f18fbb"),
                            Uf = "PE"
                        },
                        new
                        {
                            Id = new Guid("275002db-aa62-444e-a179-b801583c3568"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Piaui",
                            IdRegiao = new Guid("78fa8876-6c2d-4a09-b981-f77538f18fbb"),
                            Uf = "PI"
                        },
                        new
                        {
                            Id = new Guid("3b0458c6-5eff-4342-bd53-4591d7c006de"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Rio de Janeiro",
                            IdRegiao = new Guid("6fb578f8-5176-4906-a805-3a100adde0c9"),
                            Uf = "RJ"
                        },
                        new
                        {
                            Id = new Guid("dca93b97-5ef7-44ee-bfb4-5f63b0c72598"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Rio Grande do Norte",
                            IdRegiao = new Guid("78fa8876-6c2d-4a09-b981-f77538f18fbb"),
                            Uf = "RN"
                        },
                        new
                        {
                            Id = new Guid("6b57ce63-eb3a-4c73-8b59-8098e6862d48"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Rio Grande do Sul",
                            IdRegiao = new Guid("667589e6-12e3-44de-86cb-141058365c78"),
                            Uf = "RS"
                        },
                        new
                        {
                            Id = new Guid("12405ad1-e3e5-43fd-9bfe-0c6fa4816105"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Rondonia",
                            IdRegiao = new Guid("91ea2869-3fb0-4c39-8583-f420f8d48fa5"),
                            Uf = "RO"
                        },
                        new
                        {
                            Id = new Guid("a850fb53-9f5b-449e-b691-d084f8b5a402"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Roraima",
                            IdRegiao = new Guid("91ea2869-3fb0-4c39-8583-f420f8d48fa5"),
                            Uf = "RR"
                        },
                        new
                        {
                            Id = new Guid("dbb01ebc-4776-4f72-b630-7b249d81c440"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Santa Catarina",
                            IdRegiao = new Guid("667589e6-12e3-44de-86cb-141058365c78"),
                            Uf = "SC"
                        },
                        new
                        {
                            Id = new Guid("5e684315-735e-4c8e-a508-8df50649dc1d"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Sao Paulo",
                            IdRegiao = new Guid("6fb578f8-5176-4906-a805-3a100adde0c9"),
                            Uf = "SP"
                        },
                        new
                        {
                            Id = new Guid("6d2e386b-a450-4976-83ce-ed107120c9fb"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Sergipe",
                            IdRegiao = new Guid("78fa8876-6c2d-4a09-b981-f77538f18fbb"),
                            Uf = "SE"
                        },
                        new
                        {
                            Id = new Guid("7fdaaa4c-13ed-49d4-b1aa-ceaae53254b6"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Tocantins",
                            IdRegiao = new Guid("91ea2869-3fb0-4c39-8583-f420f8d48fa5"),
                            Uf = "TO"
                        },
                        new
                        {
                            Id = new Guid("141a0daa-47e8-49fe-8dea-0ee97e4db538"),
                            DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Distrito Federal",
                            IdRegiao = new Guid("8b985725-487b-4a32-92a5-cb708f44c54b"),
                            Uf = "DF"
                        });
                });

            modelBuilder.Entity("TechChallengeFiap.Domain.Entities.Regiao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.HasKey("Id");

                    b.ToTable("Regioes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b985725-487b-4a32-92a5-cb708f44c54b"),
                            DataCriacao = new DateTime(2024, 5, 19, 20, 47, 26, 876, DateTimeKind.Local).AddTicks(1832),
                            Descricao = "Centro-oeste"
                        },
                        new
                        {
                            Id = new Guid("6fb578f8-5176-4906-a805-3a100adde0c9"),
                            DataCriacao = new DateTime(2024, 5, 19, 20, 47, 26, 876, DateTimeKind.Local).AddTicks(1850),
                            Descricao = "Sudeste"
                        },
                        new
                        {
                            Id = new Guid("78fa8876-6c2d-4a09-b981-f77538f18fbb"),
                            DataCriacao = new DateTime(2024, 5, 19, 20, 47, 26, 876, DateTimeKind.Local).AddTicks(1852),
                            Descricao = "Nordeste"
                        },
                        new
                        {
                            Id = new Guid("667589e6-12e3-44de-86cb-141058365c78"),
                            DataCriacao = new DateTime(2024, 5, 19, 20, 47, 26, 876, DateTimeKind.Local).AddTicks(1853),
                            Descricao = "Sul"
                        },
                        new
                        {
                            Id = new Guid("91ea2869-3fb0-4c39-8583-f420f8d48fa5"),
                            DataCriacao = new DateTime(2024, 5, 19, 20, 47, 26, 876, DateTimeKind.Local).AddTicks(1855),
                            Descricao = "Norte"
                        });
                });

            modelBuilder.Entity("TechChallengeFiap.Domain.Entities.Contato", b =>
                {
                    b.HasOne("TechChallengeFiap.Domain.Entities.DDD", "DDD")
                        .WithMany("Contatos")
                        .HasForeignKey("IdDDD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DDD");
                });

            modelBuilder.Entity("TechChallengeFiap.Domain.Entities.DDD", b =>
                {
                    b.HasOne("TechChallengeFiap.Domain.Entities.Estado", "Estado")
                        .WithMany("DDDs")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("TechChallengeFiap.Domain.Entities.Estado", b =>
                {
                    b.HasOne("TechChallengeFiap.Domain.Entities.Regiao", "Regiao")
                        .WithMany("Estados")
                        .HasForeignKey("IdRegiao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regiao");
                });

            modelBuilder.Entity("TechChallengeFiap.Domain.Entities.DDD", b =>
                {
                    b.Navigation("Contatos");
                });

            modelBuilder.Entity("TechChallengeFiap.Domain.Entities.Estado", b =>
                {
                    b.Navigation("DDDs");
                });

            modelBuilder.Entity("TechChallengeFiap.Domain.Entities.Regiao", b =>
                {
                    b.Navigation("Estados");
                });
#pragma warning restore 612, 618
        }
    }
}
