name: Pipeline de CI/CD TECHCHALLENGE

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar código
      uses: actions/checkout@v2

    - name: Restaurar dependências
      run: dotnet restore

    - name: Publicar aplicação
      run: dotnet publish -c Release -o ./publish

    - name: Set up kubectl
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
        version: 1.32.7

    - name: Fazer login no registro Docker
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} | echo ${{ secrets.DOCKERHUB_PASSWORD }} 

    - name: Construir a imagem Docker
      run: docker build -t dinizfernanda/api-techchallenge:latest -f src/TechChallengeFiap.Application/Dockerfile .
        
    - name: Publicar a imagem Docker
      run: docker push dinizfernanda/api-techchallenge:latest

    - name: Construir a imagem Docker
      run: docker build -t dinizfernanda/email-techchallenge:latest -f src/TechChallengeFiap.Email/Dockerfile .
    
    - name: Publicar imagem Docker
      run: docker push dinizfernanda/email-techchallenge:latest

    - name: Listar arquivos no diretório
      run: |
        echo "Executando dir..."
        dir

    - name: Implantação no Kubernetes
      run: kubectl apply -f deployments-novo.yaml 
